### ISSUE TITLE
Daniel you forgot about Node.js

### ISSUE THREAD

**Issue by DanielFitzsimmons** [DanielFitzsimmons/the-coding-song#2]
You need to add Node.js to the song as Node is the best!

**Comment by DanielFitzsimmons** [comment]
Great idea I will do that now!

**Comment by tysonlmao** [comment]
also forgot

[A.NET (A#/A sharp)](https://en.wikipedia.org/wiki/A_Sharp_(.NET))
[A-0 System](https://en.wikipedia.org/wiki/A-0_System)
[A+ (A plus)](https://en.wikipedia.org/wiki/A%2B_(programming_language))
[ABAP](https://en.wikipedia.org/wiki/ABAP)
[ABC](https://en.wikipedia.org/wiki/ABC_(programming_language))
[ABC ALGOL](https://en.wikipedia.org/wiki/ABC_ALGOL)
[ACC](https://en.wikipedia.org/wiki/ACC_(programming_language))
[Accent (Rational Synergy)](https://en.wikipedia.org/wiki/Accent_(programming_language))
Ace [Distributed Application Specification Language](https://en.wikipedia.org/wiki/Distributed_Application_Specification_Language) (DASL)
[Action!](https://en.wikipedia.org/wiki/Action!_(programming_language))
[ActionScript](https://en.wikipedia.org/wiki/ActionScript)
[Actor](https://en.wikipedia.org/wiki/Actor_(programming_language))
[Ada](https://en.wikipedia.org/wiki/Ada_(programming_language)) – [ISO/IEC 8652](https://en.wikipedia.org/wiki/ISO/IEC_8652)
[Adenine (Haystack)](https://en.wikipedia.org/wiki/Adenine_(programming_language))
[AdvPL](https://en.wikipedia.org/wiki/AdvPL)
[Agda](https://en.wikipedia.org/wiki/Agda_(theorem_prover))
[Agilent VEE](https://en.wikipedia.org/wiki/Agilent_VEE) (Keysight VEE)
[Agora](https://en.wikipedia.org/wiki/Agora_(programming_language))
[AIMMS](https://en.wikipedia.org/wiki/AIMMS)
[Aldor](https://en.wikipedia.org/wiki/Aldor)
[Alef](https://en.wikipedia.org/wiki/Alef_(programming_language))
[ALF](https://en.wikipedia.org/wiki/Algebraic_Logic_Functional_programming_language)
[ALGOL 58](https://en.wikipedia.org/wiki/ALGOL_58)
[ALGOL 60](https://en.wikipedia.org/wiki/ALGOL_60)
[ALGOL 68](https://en.wikipedia.org/wiki/ALGOL_68)
[ALGOL W](https://en.wikipedia.org/wiki/ALGOL_W)
[Alice (Alice ML)](https://en.wikipedia.org/wiki/Alice_(programming_language))
[Alma-0](https://en.wikipedia.org/wiki/Alma-0)
[AmbientTalk](https://en.wikipedia.org/wiki/AmbientTalk)
[Amiga E](https://en.wikipedia.org/wiki/Amiga_E)
[AMPL](https://en.wikipedia.org/wiki/AMPL)
[Analitik](https://en.wikipedia.org/wiki/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D1%82%D0%B8%D0%BA)
[AngelScript](https://en.wikipedia.org/wiki/AngelScript)
[Apache Pig latin](https://en.wikipedia.org/wiki/Apache_Pig)
[Apex (Salesforce.com, Inc)](https://en.wikipedia.org/wiki/Apex_(programming_language))
[APL](https://en.wikipedia.org/wiki/APL_(programming_language))
[App Inventor for Android's visual block language (MIT App Inventor)](https://en.wikipedia.org/wiki/App_Inventor_for_Android_(programming_language))
[AppleScript](https://en.wikipedia.org/wiki/AppleScript)
[APT](https://en.wikipedia.org/wiki/APT_(programming_language))
[Arc](https://en.wikipedia.org/wiki/Arc_(programming_language))
[ARexx](https://en.wikipedia.org/wiki/ARexx)
[Argus](https://en.wikipedia.org/wiki/Argus_(programming_language))
[Assembly language (ASM)](https://en.wikipedia.org/wiki/Assembly_language)
[AutoHotkey](https://en.wikipedia.org/wiki/AutoHotkey)
[AutoIt](https://en.wikipedia.org/wiki/AutoIt)
[AutoLISP / Visual LISP](https://en.wikipedia.org/wiki/AutoLISP)
[Averest](https://en.wikipedia.org/wiki/Averest)
[AWK](https://en.wikipedia.org/wiki/AWK)
[Axum](https://en.wikipedia.org/wiki/Axum_(programming_language))
B
B
Babbage
Ballerina
Bash
BASIC
Batch file (Windows/MS-DOS)
bc (basic calculator)
BCPL
BeanShell
BETA
BLISS
Blockly
BlooP
Boo
Boomerang
Bosque
C
C – ISO/IEC 9899
C-- (C minus minus)
C++ (C plus plus) – ISO/IEC 14882
C*
C# (C sharp) – ISO/IEC 23270
C/AL
Caché ObjectScript
C Shell (csh)
Caml
Carbon
Catrobat
Cayenne (Lennart Augustsson)
CDuce
Cecil
CESIL (Computer Education in Schools Instruction Language)
Céu
Ceylon
CFEngine
Cg (High-Level Shader/Shading Language [HLSL])
Ch
Chapel (Cascade High Productivity Language)
Charm
CHILL
CHIP-8
ChucK
Cilk (also Cilk++ and Cilk plus)
Claire
Clarion
Clean
Clipper
CLIPS
CLIST
Clojure
CLU
CMS-2
CO[B](https://en.wikipedia.org/wiki/B_(programming_language))OL – ISO/IEC 1989
[C](https://en.wikipedia.org/wiki/C_(programming_language))obolScript – [COBOL](https://en.wikipedia.org/wiki/COBOL) Scripting language
[Cobra](https://en.wikipedia.org/wiki/Cobra_(programming_language))
[CoffeeScript](https://en.wikipedia.org/wiki/CoffeeScript)
[ColdFusion](https://en.wikipedia.org/wiki/ColdFusion)
[COMAL](https://en.wikipedia.org/wiki/COMAL)
[COMIT](https://en.wikipedia.org/wiki/COMIT)
[Common Intermediate Language](https://en.wikipedia.org/wiki/Common_Intermediate_Language) (CIL)
[Common Lisp](https://en.wikipedia.org/wiki/Common_Lisp) (also known as CL)
[COMPASS](https://en.wikipedia.org/wiki/COMPASS)
[Component Pascal](https://en.wikipedia.org/wiki/Component_Pascal)
[COMTRAN](https://en.wikipedia.org/wiki/COMTRAN)
[Concurrent Pascal](https://en.wikipedia.org/wiki/Concurrent_Pascal)
[Constraint Handling Rules](https://en.wikipedia.org/wiki/Constraint_Handling_Rules) (CHR)
[Control Language](https://en.wikipedia.org/wiki/Control_Language)
[Coq](https://en.wikipedia.org/wiki/Coq)
[Coral 66](https://en.wikipedia.org/wiki/Coral_66)
[CorVision](https://en.wikipedia.org/wiki/CorVision)
[COWSEL](https://en.wikipedia.org/wiki/COWSEL)
[CPL](https://en.wikipedia.org/wiki/CPL_(programming_language))
[Cryptol](https://en.wikipedia.org/wiki/Cryptol)
[Crystal](https://en.wikipedia.org/wiki/Crystal_(programming_language))
[Csound](https://en.wikipedia.org/wiki/Csound)
[Cuneiform](https://en.wikipedia.org/wiki/Cuneiform_(programming_language))
[Curl](https://en.wikipedia.org/wiki/Curl_(programming_language))
[Curry](https://en.wikipedia.org/wiki/Curry_(programming_language))
[Cybil](https://en.wikipedia.org/wiki/Cybil_(programming_language))
[Cyclone](https://en.wikipedia.org/wiki/Cyclone_(programming_language))
[Cypher Query Language](https://en.wikipedia.org/wiki/Cypher_Query_Language)
[Cython](https://en.wikipedia.org/wiki/Cython)
[CEEMAC](https://en.wikipedia.org/wiki/CEEMAC)
D
[D](https://en.wikipedia.org/wiki/D_(programming_language)) (also known as dlang)
[Dart](https://en.wikipedia.org/wiki/Dart_(programming_language))
[Darwin](https://en.wikipedia.org/wiki/Darwin_(programming_language))
[DataFlex](https://en.wikipedia.org/wiki/DataFlex)
[Datalog](https://en.wikipedia.org/wiki/Datalog)
[DATATRIEVE](https://en.wikipedia.org/wiki/DATATRIEVE)
[dBase](https://en.wikipedia.org/wiki/DBase)
[dc](https://en.wikipedia.org/wiki/Dc_(computer_program))
[DCL (DIGITAL Command Language)](https://en.wikipedia.org/wiki/DIGITAL_Command_Language)
[Delphi](https://en.wikipedia.org/wiki/Delphi_(software))
[DIBOL](https://en.wikipedia.org/wiki/DIBOL)
[DinkC](https://en.wikipedia.org/wiki/Dink_Smallwood#Modification)
[Dog](https://en.wikipedia.org/wiki/Dog_(programming_language))
[Draco](https://en.wikipedia.org/wiki/Draco_(programming_language))
[DRAKON](https://en.wikipedia.org/wiki/DRAKON)
[Dylan](https://en.wikipedia.org/wiki/Dylan_(programming_language))
[DYNAMO](https://en.wikipedia.org/wiki/DYNAMO_(programming_language))
[DAX (Data Analysis Expressions)](https://en.wikipedia.org/wiki/Data_analysis_expressions)
E
[E](https://en.wikipedia.org/wiki/E_(programming_language))
[Ease](https://en.wikipedia.org/wiki/Ease_(programming_language))
[Easy PL/I](https://en.wikipedia.org/wiki/PL/I)
[EASYTRIEVE PLUS](https://en.wikipedia.org/wiki/Easytrieve)
[eC](https://en.wikipedia.org/wiki/EC_(programming_language))
[ECMAScript](https://en.wikipedia.org/wiki/ECMAScript)
[Edinburgh IMP](https://en.wikipedia.org/wiki/Edinburgh_IMP)
[EGL](https://en.wikipedia.org/wiki/EGL_(programming_language))
[Eiffel](https://en.wikipedia.org/wiki/Eiffel_(programming_language))
[ELAN](https://en.wikipedia.org/wiki/ELAN_(programming_language))
[Elixir](https://en.wikipedia.org/wiki/Elixir_(programming_language))
[Elm](https://en.wikipedia.org/wiki/Elm_(programming_language))
[Emacs Lisp](https://en.wikipedia.org/wiki/Emacs_Lisp)
[Emerald](https://en.wikipedia.org/wiki/Emerald_(programming_language))
[Epigram](https://en.wikipedia.org/wiki/Epigram_(programming_language))
[EPL (Easy Programming Language)](https://en.wikipedia.org/wiki/Easy_Programming_Language)
[Erlang](https://en.wikipedia.org/wiki/Erlang_(programming_language))
[es](https://en.wikipedia.org/wiki/Es_(Unix_shell))
[Escher](https://en.wikipedia.org/wiki/Escher_(programming_language))
[ESPOL](https://en.wikipedia.org/wiki/Executive_Systems_Problem_Oriented_Language)
[Esterel](https://en.wikipedia.org/wiki/Esterel)
[Etoys](https://en.wikipedia.org/wiki/Etoys_(programming_language))
[Euclid](https://en.wikipedia.org/wiki/Euclid_(programming_language))
[Euler](https://en.wikipedia.org/wiki/Euler_(programming_language))
[Euphoria](https://en.wikipedia.org/wiki/Euphoria_(programming_language))
[EusLisp Robot Programming Language](https://en.wikipedia.org/wiki/EusLisp_Robot_Programming_Language)
[CMS EXEC](https://en.wikipedia.org/wiki/CMS_EXEC) (EXEC)
[EXEC 2](https://en.wikipedia.org/wiki/EXEC_2)
[Executable UML](https://en.wikipedia.org/wiki/Executable_UML)
[Ezhil](https://en.wikipedia.org/wiki/Ezhil_(programming_language))
F
[F](https://en.wikipedia.org/wiki/F_(programming_language))
[F# (F sharp)](https://en.wikipedia.org/wiki/F_Sharp_(programming_language))
[F*](https://en.wikipedia.org/wiki/F*_(programming_language))
[Factor](https://en.wikipedia.org/wiki/Factor_(programming_language))
[Fantom](https://en.wikipedia.org/wiki/Fantom_(programming_language))
[FAUST](https://en.wikipedia.org/wiki/FAUST_(programming_language))
[FFP](https://en.wikipedia.org/wiki/FFP_(programming_language))
[fish](https://en.wikipedia.org/wiki/Friendly_interactive_shell)
[Fjölnir](https://en.wikipedia.org/wiki/Fj%C3%B6lnir_(programming_language))
[FL](https://en.wikipedia.org/wiki/FL_(programming_language))
[Flavors](https://en.wikipedia.org/wiki/Flavors_(programming_language))
[Flex](https://en.wikipedia.org/wiki/Flex_(language))
[Flix](https://en.wikipedia.org/wiki/Flix_(programming_language))
[FlooP](https://en.wikipedia.org/wiki/BlooP_and_FlooP)
[FLOW-MATIC (B0)](https://en.wikipedia.org/wiki/FLOW-MATIC)
[FOCAL (Formulating On-Line Calculations in Algebraic Language/FOrmula CALculator)](https://en.wikipedia.org/wiki/FOCAL_(programming_language))
[FOCUS](https://en.wikipedia.org/wiki/FOCUS)
[FOIL](https://en.wikipedia.org/wiki/FOIL_(programming_language))
[FORMAC (FORMula MAnipulation Compiler)](https://en.wikipedia.org/wiki/FORMAC_(programming_language))
[@Formula](https://en.wikipedia.org/wiki/Formula_language)
[Forth](https://en.wikipedia.org/wiki/Forth_(programming_language))
[Fortran](https://en.wikipedia.org/wiki/Fortran) – ISO/IEC 1539
[Fortress](https://en.wikipedia.org/wiki/Fortress_(programming_language))
[FP](https://en.wikipedia.org/wiki/FP_(programming_language))
[FoxBase/FoxPro](https://en.wikipedia.org/wiki/FoxPro_(programming_language))
[Franz Lisp](https://en.wikipedia.org/wiki/Franz_Lisp)
[Futhark](https://en.wikipedia.org/wiki/Futhark_(programming_language))
[F-Script](https://en.wikipedia.org/wiki/F-Script_(programming_language))
